name: Linting and build

on:
  pull_request:
  push:

jobs:
  lint_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Hadolint Action
        uses: brpaz/hadolint-action@v1.2.1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
