name: Linting

on:
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Hadolint Action
        uses: brpaz/hadolint-action@v1.2.1
